      <p class="ch-form-row ch-form-required">
          <label for="select">Categoria:<em>*</em></label>
          <select id="select" name="select">
              <option value="-1">Selecione a categoria</option>
              <optgroup value="MLB5672" label="Acessórios para Veículos"></optgroup>
                <option value="MLB6005" <?php if($item['category_id'] == "MLB6005") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Acessórios Náutica</option>
                <option value="MLB1747" <?php if($item['category_id'] == "MLB1747") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Acessórios de Carros</option>
                <option value="MLB1771" <?php if($item['category_id'] == "MLB1771") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Acessórios de Motos</option>
                <option value="MLB1776" <?php if($item['category_id'] == "MLB1776") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Acessórios e Peças Tuning</option>
                <option value="MLB8531" <?php if($item['category_id'] == "MLB8531") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;GPS</option>
                <option value="MLB5802" <?php if($item['category_id'] == "MLB5802") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Outros</option>
                <option value="MLB6798" <?php if($item['category_id'] == "MLB6798") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Peças para 4x4</option>
                <option value="MLB22693" <?php if($item['category_id'] == "MLB22693") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Peças para Carros</option>
                <option value="MLB5768" <?php if($item['category_id'] == "MLB5768") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Restauração de Carros Antigos</option>
                <option value="MLB2238" <?php if($item['category_id'] == "MLB2238") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Rodas, Pneus e Calotas</option>
                <option value="MLB3381" <?php if($item['category_id'] == "MLB3381") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Som e Vídeo para Carro</option>
              <optgroup value="MLB1499" label="Agro, Indústria e Comércio"></optgroup>
                <option value="MLB5452" <?php if($item['category_id'] == "MLB5452") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Comércio</option>
                <option value="MLB1500" <?php if($item['category_id'] == "MLB1500") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Construção</option>
                <option value="MLB2467" <?php if($item['category_id'] == "MLB2467") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Energia Elétrica</option>
                <option value="MLB2102" <?php if($item['category_id'] == "MLB2102") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Equipamento para Escritórios</option>
                <option value="MLB5226" <?php if($item['category_id'] == "MLB5226") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ferramentas</option>
                <option value="MLB1512" <?php if($item['category_id'] == "MLB1512") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Indústria Agrícola</option>
                <option value="MLB1508" <?php if($item['category_id'] == "MLB1508") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Indústria Automotiva</option>
                <option value="MLB5446" <?php if($item['category_id'] == "MLB5446") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Indústria Gráfica e Impressão</option>
                <option value="MLB5456" <?php if($item['category_id'] == "MLB5456") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Indústria Pesada</option>
                <option value="MLB1504" <?php if($item['category_id'] == "MLB1504") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Indústria Plástica e Química</option>
                <option value="MLB5454" <?php if($item['category_id'] == "MLB5454") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Indústria Têxtil e Confecção</option>
                <option value="MLB5550" <?php if($item['category_id'] == "MLB5550") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Medições e Instrumentação</option>
                <option value="MLB1893" <?php if($item['category_id'] == "MLB1893") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Outros</option>
                <option value="MLB6416" <?php if($item['category_id'] == "MLB6416") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Reciclagem</option>
              <optgroup value="MLB1071" label="Animais"></optgroup>
                <option value="MLB1100" <?php if($item['category_id'] == "MLB1100") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Aves</option>
                <option value="MLB1072" <?php if($item['category_id'] == "MLB1072") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cachorros</option>
                <option value="MLB1117" <?php if($item['category_id'] == "MLB1117") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cavalos</option>
                <option value="MLB1081" <?php if($item['category_id'] == "MLB1081") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Gatos</option>
                <option value="MLB3615" <?php if($item['category_id'] == "MLB3615") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Livros e Revistas de Animais</option>
                <option value="MLB1126" <?php if($item['category_id'] == "MLB1126") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Outros</option>
                <option value="MLB1091" <?php if($item['category_id'] == "MLB1091") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Peixes</option>
                <option value="MLB1105" <?php if($item['category_id'] == "MLB1105") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Roedores</option>
              <optgroup value="MLB1367" label="Antiguidades"></optgroup>
                <option value="MLB9172" <?php if($item['category_id'] == "MLB9172") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Acessórios de Cozinha Antigos</option>
                <option value="MLB30205" <?php if($item['category_id'] == "MLB30205") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Balanças Antigas</option>
                <option value="MLB9197" <?php if($item['category_id'] == "MLB9197") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Bicicletas Antigas</option>
                <option value="MLB39568" <?php if($item['category_id'] == "MLB39568") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Brinquedos Antigos</option>
                <option value="MLB40210" <?php if($item['category_id'] == "MLB40210") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Câmeras Antigas</option>
                <option value="MLB5467" <?php if($item['category_id'] == "MLB5467") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Decoração Antiga</option>
                <option value="MLB40278" <?php if($item['category_id'] == "MLB40278") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Eletrodomésticos Antigos</option>
                <option value="MLB40184" <?php if($item['category_id'] == "MLB40184") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ferramentas Antigas</option>
                <option value="MLB5466" <?php if($item['category_id'] == "MLB5466") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Iluminação Antiga</option>
                <option value="MLB5561" <?php if($item['category_id'] == "MLB5561") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Latas Antigas</option>
                <option value="MLB5518" <?php if($item['category_id'] == "MLB5518") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Moedores Antigos</option>
                <option value="MLB5476" <?php if($item['category_id'] == "MLB5476") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Máquinas de Escrever Antigas</option>
                <option value="MLB5462" <?php if($item['category_id'] == "MLB5462") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Móveis Antigos</option>
                <option value="MLB40288" <?php if($item['category_id'] == "MLB40288") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Navalhas Antigas</option>
                <option value="MLB5457" <?php if($item['category_id'] == "MLB5457") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Outras Antiguidades</option>
                <option value="MLB34367" <?php if($item['category_id'] == "MLB34367") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Portas e Janelas Antigas</option>
                <option value="MLB5519" <?php if($item['category_id'] == "MLB5519") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Relógios Antigos</option>
                <option value="MLB40211" <?php if($item['category_id'] == "MLB40211") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Roupas e Acessórios Antigos</option>
                <option value="MLB5474" <?php if($item['category_id'] == "MLB5474") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Som Antigo</option>
                <option value="MLB5461" <?php if($item['category_id'] == "MLB5461") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Telefones Antigos</option>
              <optgroup value="MLB1368" label="Arte e Artesanato"></optgroup>
                <option value="MLB5460" <?php if($item['category_id'] == "MLB5460") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Artesanato</option>
                <option value="MLB2662" <?php if($item['category_id'] == "MLB2662") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Esculturas</option>
                <option value="MLB40285" <?php if($item['category_id'] == "MLB40285") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ferramentas e Materiais</option>
                <option value="MLB1370" <?php if($item['category_id'] == "MLB1370") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Gravuras</option>
                <option value="MLB5464" <?php if($item['category_id'] == "MLB5464") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Livros</option>
                <option value="MLB1371" <?php if($item['category_id'] == "MLB1371") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Outros</option>
                <option value="MLB1369" <?php if($item['category_id'] == "MLB1369") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Pinturas</option>
              <optgroup value="MLB1384" label="Bebês"></optgroup>
                <option value="MLB5360" <?php if($item['category_id'] == "MLB5360") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Alimentação para Bebê</option>
                <option value="MLB5373" <?php if($item['category_id'] == "MLB5373") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Banho, Saúde e Higiene do Bebê</option>
                <option value="MLB5362" <?php if($item['category_id'] == "MLB5362") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Berços e Móveis para Bebês</option>
                <option value="MLB1392" <?php if($item['category_id'] == "MLB1392") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Brinquedos para Bebês</option>
                <option value="MLB40554" <?php if($item['category_id'] == "MLB40554") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cadeiras de Alimentação</option>
                <option value="MLB1387" <?php if($item['category_id'] == "MLB1387") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cadeiras de Bebê para Carro</option>
                <option value="MLB1386" <?php if($item['category_id'] == "MLB1386") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Carrinhos para Bebê</option>
                <option value="MLB1889" <?php if($item['category_id'] == "MLB1889") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Decoração e Lembranças de Bebê</option>
                <option value="MLB74368" <?php if($item['category_id'] == "MLB74368") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Fraldas e Bolsas de Bebê</option>
                <option value="MLB6156" <?php if($item['category_id'] == "MLB6156") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Outros</option>
                <option value="MLB1396" <?php if($item['category_id'] == "MLB1396") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Roupas de Bebê</option>
                <option value="MLB5358" <?php if($item['category_id'] == "MLB5358") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Segurança para Bebê</option>
              <optgroup value="MLB1132" label="Brinquedos e Hobbies"></optgroup>
                <option value="MLB6911" <?php if($item['category_id'] == "MLB6911") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ar Livre, Malabares e Festas</option>
                <option value="MLB2968" <?php if($item['category_id'] == "MLB2968") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Bonecas e Acessórios</option>
                <option value="MLB1839" <?php if($item['category_id'] == "MLB1839") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Bonecos e Figuras de Ação</option>
                <option value="MLB2533" <?php if($item['category_id'] == "MLB2533") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Brinquedos</option>
                <option value="MLB2963" <?php if($item['category_id'] == "MLB2963") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Brinquedos de Controle Remoto</option>
                <option value="MLB3655" <?php if($item['category_id'] == "MLB3655") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Brinquedos para Bebês</option>
                <option value="MLB1133" <?php if($item['category_id'] == "MLB1133") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cards e Card Games </option>
                <option value="MLB6881" <?php if($item['category_id'] == "MLB6881") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Filmes Infantis</option>
                <option value="MLB2960" <?php if($item['category_id'] == "MLB2960") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Jogos</option>
                <option value="MLB1157" <?php if($item['category_id'] == "MLB1157") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lego e Blocos de Montar</option>
                <option value="MLB6905" <?php if($item['category_id'] == "MLB6905") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Mini Veículos e Bicicletas</option>
                <option value="MLB1841" <?php if($item['category_id'] == "MLB1841") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Modelismo Profissional</option>
                <option value="MLB51397" <?php if($item['category_id'] == "MLB51397") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Música Infantil</option>
                <option value="MLB1910" <?php if($item['category_id'] == "MLB1910") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Outros</option>
                <option value="MLB1166" <?php if($item['category_id'] == "MLB1166") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Pelúcias e Afins</option>
                <option value="MLB2097" <?php if($item['category_id'] == "MLB2097") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Veículos em Miniatura</option>
              <optgroup value="MLB1430" label="Calçados, Roupas e Bolsas"></optgroup>
                <option value="MLB1451" <?php if($item['category_id'] == "MLB1451") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Acessórios</option>
                <option value="MLB7022" <?php if($item['category_id'] == "MLB7022") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Bolsas</option>
                <option value="MLB108782" <?php if($item['category_id'] == "MLB108782") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Calças , Shorts e Bermudas</option>
                <option value="MLB107292" <?php if($item['category_id'] == "MLB107292") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Camisas</option>
                <option value="MLB3122" <?php if($item['category_id'] == "MLB3122") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Camisetas e Blusas</option>
                <option value="MLB108803" <?php if($item['category_id'] == "MLB108803") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Casacos, Jaquetas e Coletes</option>
                <option value="MLB28162" <?php if($item['category_id'] == "MLB28162") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Conjuntos Infantis</option>
                <option value="MLB27250" <?php if($item['category_id'] == "MLB27250") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Macacões</option>
                <option value="MLB1457" <?php if($item['category_id'] == "MLB1457") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Malas e Carteiras </option>
                <option value="MLB3127" <?php if($item['category_id'] == "MLB3127") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Mochilas</option>
                <option value="MLB1911" <?php if($item['category_id'] == "MLB1911") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Outros</option>
                <option value="MLB108838" <?php if($item['category_id'] == "MLB108838") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Roupa de Banho</option>
                <option value="MLB108786" <?php if($item['category_id'] == "MLB108786") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Roupa Íntima e Lingerie</option>
                <option value="MLB5366" <?php if($item['category_id'] == "MLB5366") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Roupas para Bebês</option>
                <option value="MLB23262" <?php if($item['category_id'] == "MLB23262") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Sapatos</option>
                <option value="MLB108831" <?php if($item['category_id'] == "MLB108831") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ternos</option>
                <option value="MLB23332" <?php if($item['category_id'] == "MLB23332") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tênis Esportivos</option>
                <option value="MLB12554" <?php if($item['category_id'] == "MLB12554") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Uniformes Escolares</option>
                <option value="MLB108707" <?php if($item['category_id'] == "MLB108707") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Vestidos e Saias</option>
                <option value="MLB1456" <?php if($item['category_id'] == "MLB1456") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Óculos</option>
              <optgroup value="MLB1039" label="Câmeras e Acessórios"></optgroup>
                <option value="MLB1049" <?php if($item['category_id'] == "MLB1049") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Acessórios para Câmeras</option>
                <option value="MLB4893" <?php if($item['category_id'] == "MLB4893") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cartões de Memória</option>
                <option value="MLB1985" <?php if($item['category_id'] == "MLB1985") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Câmeras Analógicas e Polaroid</option>
                <option value="MLB1042" <?php if($item['category_id'] == "MLB1042") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Câmeras Digitais</option>
                <option value="MLB100714" <?php if($item['category_id'] == "MLB100714") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Câmeras Profissionais e Lentes</option>
                <option value="MLB1048" <?php if($item['category_id'] == "MLB1048") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Equipamento de Revelação</option>
                <option value="MLB101144" <?php if($item['category_id'] == "MLB101144") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Filmadoras Analógicas</option>
                <option value="MLB6989" <?php if($item['category_id'] == "MLB6989") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Filmadoras Digitais</option>
                <option value="MLB4062" <?php if($item['category_id'] == "MLB4062") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Instrumentos Ópticos </option>
                <option value="MLB1914" <?php if($item['category_id'] == "MLB1914") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Outros</option>
                <option value="MLB4239" <?php if($item['category_id'] == "MLB4239") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Pilhas, Carregadores e Bateria</option>
              <optgroup value="MLB1743" label="Carros, Motos e Outros"></optgroup>
                <option value="MLB5839" <?php if($item['category_id'] == "MLB5839") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Caminhões</option>
                <option value="MLB1744" <?php if($item['category_id'] == "MLB1744") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Carros</option>
                <option value="MLB1745" <?php if($item['category_id'] == "MLB1745") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Carros Antigos</option>
                <option value="MLB1763" <?php if($item['category_id'] == "MLB1763") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Motos</option>
                <option value="MLB1785" <?php if($item['category_id'] == "MLB1785") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Náutica</option>
                <option value="MLB1907" <?php if($item['category_id'] == "MLB1907") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Outros Veículos</option>
                <option value="MLB47400" <?php if($item['category_id'] == "MLB47400") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ônibus</option>
              <optgroup value="MLB1574" label="Casa, Móveis e Decoração"></optgroup>
                <option value="MLB117798" <?php if($item['category_id'] == "MLB117798") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Artigos de Natal</option>
                <option value="MLB1613" <?php if($item['category_id'] == "MLB1613") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Banho</option>
                <option value="MLB14548" <?php if($item['category_id'] == "MLB14548") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Chãos e Paredes</option>
                <option value="MLB1618" <?php if($item['category_id'] == "MLB1618") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cozinha</option>
                <option value="MLB1631" <?php if($item['category_id'] == "MLB1631") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Decoração</option>
                <option value="MLB2525" <?php if($item['category_id'] == "MLB2525") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ferramentas</option>
                <option value="MLB1582" <?php if($item['category_id'] == "MLB1582") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Iluminação</option>
                <option value="MLB1621" <?php if($item['category_id'] == "MLB1621") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Jardins e Exteriores</option>
                <option value="MLB3236" <?php if($item['category_id'] == "MLB3236") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Living e Sala de Jantar</option>
                <option value="MLB3240" <?php if($item['category_id'] == "MLB3240") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Móveis para Escritório</option>
                <option value="MLB1902" <?php if($item['category_id'] == "MLB1902") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Outros</option>
                <option value="MLB1608" <?php if($item['category_id'] == "MLB1608") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Quarto</option>
                <option value="MLB7069" <?php if($item['category_id'] == "MLB7069") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Segurança para Casa</option>
              <optgroup value="MLB1051" label="Celulares e Telefones"></optgroup>
                <option value="MLB3813" <?php if($item['category_id'] == "MLB3813") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Acessórios para Celulares</option>
                <option value="MLB7475" <?php if($item['category_id'] == "MLB7475") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cartões de Memória</option>
                <option value="MLB1055" <?php if($item['category_id'] == "MLB1055") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Celulares</option>
                <option value="MLB5427" <?php if($item['category_id'] == "MLB5427") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nextel</option>
                <option value="MLB1915" <?php if($item['category_id'] == "MLB1915") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Outros</option>
                <option value="MLB1058" <?php if($item['category_id'] == "MLB1058") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Rádio Amador</option>
                <option value="MLB46195" <?php if($item['category_id'] == "MLB46195") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Telefones</option>
                <option value="MLB7502" <?php if($item['category_id'] == "MLB7502") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;VoIP</option>
                <option value="MLB2908" <?php if($item['category_id'] == "MLB2908") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Walkie - Talkies</option>
              <optgroup value="MLB1798" label="Coleções e Comics"></optgroup>
                <option value="MLB3415" <?php if($item['category_id'] == "MLB3415") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Bonecas e Acessórios</option>
                <option value="MLB3422" <?php if($item['category_id'] == "MLB3422") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Bonecos e Figuras de Ação</option>
                <option value="MLB2098" <?php if($item['category_id'] == "MLB2098") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Canetas, Lápis e Afins</option>
                <option value="MLB3390" <?php if($item['category_id'] == "MLB3390") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cards / Card Games</option>
                <option value="MLB1807" <?php if($item['category_id'] == "MLB1807") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cartões Postais</option>
                <option value="MLB1830" <?php if($item['category_id'] == "MLB1830") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cartões Telefônicos</option>
                <option value="MLB2356" <?php if($item['category_id'] == "MLB2356") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Chaveiros</option>
                <option value="MLB2355" <?php if($item['category_id'] == "MLB2355") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Coleções Diversas</option>
                <option value="MLB1806" <?php if($item['category_id'] == "MLB1806") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cédulas e Moedas</option>
                <option value="MLB1805" <?php if($item['category_id'] == "MLB1805") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Espadas e Artigos Militares</option>
                <option value="MLB1861" <?php if($item['category_id'] == "MLB1861") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Filatelia</option>
                <option value="MLB3435" <?php if($item['category_id'] == "MLB3435") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;HQs e Mangás</option>
                <option value="MLB2099" <?php if($item['category_id'] == "MLB2099") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Isqueiros</option>
                <option value="MLB2314" <?php if($item['category_id'] == "MLB2314") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Latas, Garrafas e Afins</option>
                <option value="MLB2458" <?php if($item['category_id'] == "MLB2458") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Outros</option>
                <option value="MLB2456" <?php if($item['category_id'] == "MLB2456") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Publicações e Afins</option>
                <option value="MLB1834" <?php if($item['category_id'] == "MLB1834") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Pôsteres e Fotografias</option>
                <option value="MLB4489" <?php if($item['category_id'] == "MLB4489") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Revistas de Coleção</option>
                <option value="MLB3398" <?php if($item['category_id'] == "MLB3398") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Veículos em Miniatura</option>
                <option value="MLB1831" <?php if($item['category_id'] == "MLB1831") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Álbuns e Figurinhas</option>
              <optgroup value="MLB5726" label="Eletrodomésticos"></optgroup>
                <option value="MLB21171" <?php if($item['category_id'] == "MLB21171") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Bebedouros e Purificadores</option>
                <option value="MLB50495" <?php if($item['category_id'] == "MLB50495") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Coifas</option>
                <option value="MLB1581" <?php if($item['category_id'] == "MLB1581") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Eletroportáteis</option>
                <option value="MLB1580" <?php if($item['category_id'] == "MLB1580") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Forno e Fogões</option>
                <option value="MLB1576" <?php if($item['category_id'] == "MLB1576") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Geladeiras e Freezers</option>
                <option value="MLB21168" <?php if($item['category_id'] == "MLB21168") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lava Roupas e Secadoras </option>
                <option value="MLB73046" <?php if($item['category_id'] == "MLB73046") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lavalouças</option>
                <option value="MLB1899" <?php if($item['category_id'] == "MLB1899") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Outros</option>
                <option value="MLB16034" <?php if($item['category_id'] == "MLB16034") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Suportes</option>
                <option value="MLB16014" <?php if($item['category_id'] == "MLB16014") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Televisores</option>
                <option value="MLB1644" <?php if($item['category_id'] == "MLB1644") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ventilação</option>
              <optgroup value="MLB1000" label="Eletrônicos, Áudio e Vídeo"></optgroup>
                <option value="MLB4887" <?php if($item['category_id'] == "MLB4887") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Acessórios para Áudio e Vídeo</option>
                <option value="MLB1001" <?php if($item['category_id'] == "MLB1001") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Aparelhos DVD e Bluray</option>
                <option value="MLB4900" <?php if($item['category_id'] == "MLB4900") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Bateria, Pilhas e Carregadores</option>
                <option value="MLB1060" <?php if($item['category_id'] == "MLB1060") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Calculadoras e Agendas</option>
                <option value="MLB31420" <?php if($item['category_id'] == "MLB31420") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Copiadoras e  Acessórios</option>
                <option value="MLB82068" <?php if($item['category_id'] == "MLB82068") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;E-Books</option>
                <option value="MLB101214" <?php if($item['category_id'] == "MLB101214") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Filmadoras Analógicas</option>
                <option value="MLB1006" <?php if($item['category_id'] == "MLB1006") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Filmadoras Digitais</option>
                <option value="MLB3571" <?php if($item['category_id'] == "MLB3571") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;GPS</option>
                <option value="MLB6800" <?php if($item['category_id'] == "MLB6800") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Home Theaters</option>
                <option value="MLB3846" <?php if($item['category_id'] == "MLB3846") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;MP3, MP4 e MP5 Players</option>
                <option value="MLB4901" <?php if($item['category_id'] == "MLB4901") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Outros Eletrônicos</option>
                <option value="MLB6999" <?php if($item['category_id'] == "MLB6999") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Peças e Componentes Elétricos</option>
                <option value="MLB11830" <?php if($item['category_id'] == "MLB11830") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Porta Retratos Digitais</option>
                <option value="MLB2830" <?php if($item['category_id'] == "MLB2830") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Projetores e Telas</option>
                <option value="MLB2912" <?php if($item['category_id'] == "MLB2912") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Segurança para Casa</option>
                <option value="MLB1023" <?php if($item['category_id'] == "MLB1023") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Som e Vídeo Automotivo</option>
                <option value="MLB3690" <?php if($item['category_id'] == "MLB3690") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Suportes</option>
                <option value="MLB1007" <?php if($item['category_id'] == "MLB1007") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TV a Cabo e Via Satélite</option>
                <option value="MLB1002" <?php if($item['category_id'] == "MLB1002") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TV, LCD, LED e Plasma</option>
                <option value="MLB82048" <?php if($item['category_id'] == "MLB82048") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;iPad e Tablets</option>
                <option value="MLB9622" <?php if($item['category_id'] == "MLB9622") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;iPod</option>
                <option value="MLB3836" <?php if($item['category_id'] == "MLB3836") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Áudio Portátil</option>
                <option value="MLB3837" <?php if($item['category_id'] == "MLB3837") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Áudio Profissional e DJs</option>
                <option value="MLB3835" <?php if($item['category_id'] == "MLB3835") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Áudio para Casa</option>
              <optgroup value="MLB1276" label="Esportes e Fitness"></optgroup>
                <option value="MLB1338" <?php if($item['category_id'] == "MLB1338") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Aeróbica e Fitness</option>
                <option value="MLB2480" <?php if($item['category_id'] == "MLB2480") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Artes Marciais e Boxe</option>
                <option value="MLB10539" <?php if($item['category_id'] == "MLB10539") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Baseball</option>
                <option value="MLB1309" <?php if($item['category_id'] == "MLB1309") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Basquete</option>
                <option value="MLB1362" <?php if($item['category_id'] == "MLB1362") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Camping</option>
                <option value="MLB1292" <?php if($item['category_id'] == "MLB1292") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ciclismo</option>
                <option value="MLB1277" <?php if($item['category_id'] == "MLB1277") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Esportes Aquáticos</option>
                <option value="MLB1355" <?php if($item['category_id'] == "MLB1355") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Esportes de Aventura e Ação</option>
                <option value="MLB1286" <?php if($item['category_id'] == "MLB1286") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Futebol</option>
                <option value="MLB1302" <?php if($item['category_id'] == "MLB1302") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Futebol Americano</option>
                <option value="MLB9900" <?php if($item['category_id'] == "MLB9900") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Golfe</option>
                <option value="MLB1358" <?php if($item['category_id'] == "MLB1358") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Outros</option>
                <option value="MLB1293" <?php if($item['category_id'] == "MLB1293") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Patins e Skate</option>
                <option value="MLB6796" <?php if($item['category_id'] == "MLB6796") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Pesca</option>
                <option value="MLB80357" <?php if($item['category_id'] == "MLB80357") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Protetores Esportivos</option>
                <option value="MLB3900" <?php if($item['category_id'] == "MLB3900") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tênis Esportivos</option>
                <option value="MLB10536" <?php if($item['category_id'] == "MLB10536") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tênis de Mesa</option>
                <option value="MLB1322" <?php if($item['category_id'] == "MLB1322") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tênis e Squash</option>
                <option value="MLB1333" <?php if($item['category_id'] == "MLB1333") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Vôlei</option>
              <optgroup value="MLB3281" label="Filmes e Seriados"></optgroup>
                <option value="MLB40440" <?php if($item['category_id'] == "MLB40440") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Camisetas de Cinema e TV</option>
                <option value="MLB1169" <?php if($item['category_id'] == "MLB1169") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Filmes</option>
                <option value="MLB40435" <?php if($item['category_id'] == "MLB40435") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Memorabilia de Cinema e TV</option>
                <option value="MLB40412" <?php if($item['category_id'] == "MLB40412") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Outros</option>
                <option value="MLB40452" <?php if($item['category_id'] == "MLB40452") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Porta DVDs, Caixas e Envelopes</option>
                <option value="MLB6217" <?php if($item['category_id'] == "MLB6217") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Seriados</option>
              <optgroup value="MLB1144" label="Games"></optgroup>
                <option value="MLB4392" <?php if($item['category_id'] == "MLB4392") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Dreamcast</option>
                <option value="MLB51149" <?php if($item['category_id'] == "MLB51149") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Fliperama</option>
                <option value="MLB4396" <?php if($item['category_id'] == "MLB4396") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Game Boy Advance</option>
                <option value="MLB4394" <?php if($item['category_id'] == "MLB4394") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Gamecube </option>
                <option value="MLB1154" <?php if($item['category_id'] == "MLB1154") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Jogos para PC e Joysticks</option>
                <option value="MLB4400" <?php if($item['category_id'] == "MLB4400") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Mega Drive</option>
                <option value="MLB106883" <?php if($item['category_id'] == "MLB106883") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nintendo 3DS</option>
                <option value="MLB4395" <?php if($item['category_id'] == "MLB4395") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nintendo 64</option>
                <option value="MLB6758" <?php if($item['category_id'] == "MLB6758") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nintendo DS</option>
                <option value="MLB1152" <?php if($item['category_id'] == "MLB1152") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Outros Consoles</option>
                <option value="MLB106884" <?php if($item['category_id'] == "MLB106884") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;PS Vita</option>
                <option value="MLB11623" <?php if($item['category_id'] == "MLB11623") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;PlayStation 3</option>
                <option value="MLB4393" <?php if($item['category_id'] == "MLB4393") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Playstation 2</option>
                <option value="MLB4390" <?php if($item['category_id'] == "MLB4390") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Playstation One</option>
                <option value="MLB6771" <?php if($item['category_id'] == "MLB6771") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Sony PSP</option>
                <option value="MLB4378" <?php if($item['category_id'] == "MLB4378") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Super Nintendo</option>
                <option value="MLB11223" <?php if($item['category_id'] == "MLB11223") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Wii</option>
                <option value="MLB4391" <?php if($item['category_id'] == "MLB4391") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Xbox</option>
                <option value="MLB10030" <?php if($item['category_id'] == "MLB10030") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Xbox 360</option>
              <optgroup value="MLB1459" label="Imóveis"></optgroup>
                <option value="MLB1472" <?php if($item['category_id'] == "MLB1472") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Apartamento</option>
                <option value="MLB1466" <?php if($item['category_id'] == "MLB1466") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Casa</option>
                <option value="MLB1478" <?php if($item['category_id'] == "MLB1478") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Comercial - Industrial</option>
                <option value="MLB1496" <?php if($item['category_id'] == "MLB1496") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Fazenda - Sítio - Chácara</option>
                <option value="MLB1460" <?php if($item['category_id'] == "MLB1460") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Flat - Apart Hotel</option>
                <option value="MLB1892" <?php if($item['category_id'] == "MLB1892") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Outro Imóvel</option>
                <option value="MLB1493" <?php if($item['category_id'] == "MLB1493") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Terrenos - Lotes</option>
              <optgroup value="MLB1648" label="Informática"></optgroup>
                <option value="MLB5940" <?php if($item['category_id'] == "MLB5940") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Acessórios de PC</option>
                <option value="MLB3377" <?php if($item['category_id'] == "MLB3377") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Acessórios para Notebook</option>
                <option value="MLB1718" <?php if($item['category_id'] == "MLB1718") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Alimentação para PCs</option>
                <option value="MLB1870" <?php if($item['category_id'] == "MLB1870") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Apple</option>
                <option value="MLB1712" <?php if($item['category_id'] == "MLB1712") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Componentes para PC</option>
                <option value="MLB1655" <?php if($item['category_id'] == "MLB1655") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Copiadoras e  Acessórios</option>
                <option value="MLB5875" <?php if($item['category_id'] == "MLB5875") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Impressoras e Acessórios</option>
                <option value="MLB1694" <?php if($item['category_id'] == "MLB1694") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Memórias RAM</option>
                <option value="MLB14370" <?php if($item['category_id'] == "MLB14370") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Monitores</option>
                <option value="MLB3379" <?php if($item['category_id'] == "MLB3379") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Mídias Virgens</option>
                <option value="MLB1652" <?php if($item['category_id'] == "MLB1652") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Notebooks e Netbooks</option>
                <option value="MLB1912" <?php if($item['category_id'] == "MLB1912") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Outros</option>
                <option value="MLB1649" <?php if($item['category_id'] == "MLB1649") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;PC</option>
                <option value="MLB1651" <?php if($item['category_id'] == "MLB1651") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Palms e Handhelds</option>
                <option value="MLB4980" <?php if($item['category_id'] == "MLB4980") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Pen Drives</option>
                <option value="MLB1693" <?php if($item['category_id'] == "MLB1693") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Processadores</option>
                <option value="MLB1723" <?php if($item['category_id'] == "MLB1723") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Programas e Software </option>
                <option value="MLB1657" <?php if($item['category_id'] == "MLB1657") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Projetores e Telas</option>
                <option value="MLB1700" <?php if($item['category_id'] == "MLB1700") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Redes e Wi-Fi</option>
                <option value="MLB91757" <?php if($item['category_id'] == "MLB91757") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;iPad e Tablets</option>
              <optgroup value="MLB1182" label="Instrumentos Musicais"></optgroup>
                <option value="MLB7822" <?php if($item['category_id'] == "MLB7822") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Acessórios Musicais</option>
                <option value="MLB8055" <?php if($item['category_id'] == "MLB8055") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Acordeons</option>
                <option value="MLB3011" <?php if($item['category_id'] == "MLB3011") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Amplificadores</option>
                <option value="MLB3018" <?php if($item['category_id'] == "MLB3018") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Baixos</option>
                <option value="MLB3004" <?php if($item['category_id'] == "MLB3004") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Baterias e Percussão</option>
                <option value="MLB5347" <?php if($item['category_id'] == "MLB5347") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cavaquinhos</option>
                <option value="MLB4474" <?php if($item['category_id'] == "MLB4474") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Equipamento para DJ</option>
                <option value="MLB2987" <?php if($item['category_id'] == "MLB2987") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Guitarras</option>
                <option value="MLB4479" <?php if($item['category_id'] == "MLB4479") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Metrônomos e Afinadores</option>
                <option value="MLB3014" <?php if($item['category_id'] == "MLB3014") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Outros</option>
                <option value="MLB4464" <?php if($item['category_id'] == "MLB4464") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Outros Instrumentos de Corda</option>
                <option value="MLB3005" <?php if($item['category_id'] == "MLB3005") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Outros Instrumentos de Sopro</option>
                <option value="MLB3007" <?php if($item['category_id'] == "MLB3007") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Pedais e Efeitos de Som</option>
                <option value="MLB3022" <?php if($item['category_id'] == "MLB3022") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Pianos, Órgãos e Teclados</option>
                <option value="MLB3771" <?php if($item['category_id'] == "MLB3771") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Saxofones</option>
                <option value="MLB5356" <?php if($item['category_id'] == "MLB5356") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Violinos</option>
                <option value="MLB3015" <?php if($item['category_id'] == "MLB3015") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Violões</option>
                <option value="MLB4467" <?php if($item['category_id'] == "MLB4467") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Áudio Profissional</option>
              <optgroup value="MLB3937" label="Jóias e Relógios"></optgroup>
                <option value="MLB1431" <?php if($item['category_id'] == "MLB1431") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Jóias</option>
                <option value="MLB5141" <?php if($item['category_id'] == "MLB5141") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Monitores Cardíacos</option>
                <option value="MLB3938" <?php if($item['category_id'] == "MLB3938") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Outros</option>
                <option value="MLB1441" <?php if($item['category_id'] == "MLB1441") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Pedras Preciosas</option>
                <option value="MLB5122" <?php if($item['category_id'] == "MLB5122") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Piercings</option>
                <option value="MLB5478" <?php if($item['category_id'] == "MLB5478") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Relógios Antigos e de Coleção</option>
                <option value="MLB5148" <?php if($item['category_id'] == "MLB5148") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Relógios Despertadores</option>
                <option value="MLB5124" <?php if($item['category_id'] == "MLB5124") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Relógios de Bolso</option>
                <option value="MLB26426" <?php if($item['category_id'] == "MLB26426") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Relógios de Pulso</option>
                <option value="MLB12871" <?php if($item['category_id'] == "MLB12871") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Semi - Jóias</option>
              <optgroup value="MLB1196" label="Livros"></optgroup>
                <option value="MLB11466" <?php if($item['category_id'] == "MLB11466") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Catálogos</option>
                <option value="MLB1199" <?php if($item['category_id'] == "MLB1199") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;E-Books</option>
                <option value="MLB4014" <?php if($item['category_id'] == "MLB4014") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Literatura Estrangeira</option>
                <option value="MLB4505" <?php if($item['category_id'] == "MLB4505") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Literatura Nacional</option>
                <option value="MLB11464" <?php if($item['category_id'] == "MLB11464") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Livros Didáticos e de Educação</option>
                <option value="MLB11440" <?php if($item['category_id'] == "MLB11440") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Livros Infantis e Juvenis</option>
                <option value="MLB1226" <?php if($item['category_id'] == "MLB1226") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Livros Raros e Antigos</option>
                <option value="MLB3029" <?php if($item['category_id'] == "MLB3029") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Livros Universitários</option>
                <option value="MLB11444" <?php if($item['category_id'] == "MLB11444") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Livros de Áreas de Interesse</option>
                <option value="MLB1227" <?php if($item['category_id'] == "MLB1227") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Outros</option>
                <option value="MLB1222" <?php if($item['category_id'] == "MLB1222") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Revistas</option>
              <optgroup value="MLB1953" label="Mais Categorias"></optgroup>
                <option value="MLB2818" <?php if($item['category_id'] == "MLB2818") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Adultos</option>
                <option value="MLB1403" <?php if($item['category_id'] == "MLB1403") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Delicatessen</option>
                <option value="MLB1740" <?php if($item['category_id'] == "MLB1740") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Esoterismo e Ocultismo</option>
                <option value="MLB44011" <?php if($item['category_id'] == "MLB44011") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Materiais Escolares</option>
                <option value="MLB3530" <?php if($item['category_id'] == "MLB3530") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Outros</option>
              <optgroup value="MLB1168" label="Música"></optgroup>
                <option value="MLB4488" <?php if($item['category_id'] == "MLB4488") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Camisetas de Música</option>
                <option value="MLB6241" <?php if($item['category_id'] == "MLB6241") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Memorabilia de Música</option>
                <option value="MLB1174" <?php if($item['category_id'] == "MLB1174") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Música</option>
                <option value="MLB2142" <?php if($item['category_id'] == "MLB2142") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Música Infantil</option>
                <option value="MLB1228" <?php if($item['category_id'] == "MLB1228") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Outros</option>
                <option value="MLB3362" <?php if($item['category_id'] == "MLB3362") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Porta CDs, Caixas e Envelopes</option>
              <optgroup value="MLB1246" label="Saúde e Beleza"></optgroup>
                <option value="MLB1263" <?php if($item['category_id'] == "MLB1263") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cuidados com o Cabelo</option>
                <option value="MLB1260" <?php if($item['category_id'] == "MLB1260") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cuidados com o Corpo</option>
                <option value="MLB1253" <?php if($item['category_id'] == "MLB1253") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cuidados com o Rosto</option>
                <option value="MLB29884" <?php if($item['category_id'] == "MLB29884") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cuidados de Mãos</option>
                <option value="MLB1248" <?php if($item['category_id'] == "MLB1248") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Maquiagem</option>
                <option value="MLB1275" <?php if($item['category_id'] == "MLB1275") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Outros</option>
                <option value="MLB1271" <?php if($item['category_id'] == "MLB1271") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Perfumes e Fragrâncias</option>
                <option value="MLB6182" <?php if($item['category_id'] == "MLB6182") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Saúde Dental</option>
              <optgroup value="MLB1540" label="Serviços"></optgroup>
                <option value="MLB63920" <?php if($item['category_id'] == "MLB63920") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Academia e Esportes</option>
                <option value="MLB63955" <?php if($item['category_id'] == "MLB63955") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Animais</option>
                <option value="MLB63916" <?php if($item['category_id'] == "MLB63916") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Beleza, Estética e Bem Estar</option>
                <option value="MLB63939" <?php if($item['category_id'] == "MLB63939") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Casa e Decoração</option>
                <option value="MLB9080" <?php if($item['category_id'] == "MLB9080") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Construção e Manutenção</option>
                <option value="MLB1563" <?php if($item['category_id'] == "MLB1563") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Educação</option>
                <option value="MLB9141" <?php if($item['category_id'] == "MLB9141") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Festas e Eventos</option>
                <option value="MLB63895" <?php if($item['category_id'] == "MLB63895") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Floricultura</option>
                <option value="MLB110740" <?php if($item['category_id'] == "MLB110740") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Gastronomia</option>
                <option value="MLB63953" <?php if($item['category_id'] == "MLB63953") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Gráficas e Impressão</option>
                <option value="MLB63901" <?php if($item['category_id'] == "MLB63901") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Marketing e Internet</option>
                <option value="MLB1541" <?php if($item['category_id'] == "MLB1541") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Outros Profissionais</option>
                <option value="MLB1898" <?php if($item['category_id'] == "MLB1898") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Outros Serviços</option>
                <option value="MLB63937" <?php if($item['category_id'] == "MLB63937") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Saúde</option>
                <option value="MLB49258" <?php if($item['category_id'] == "MLB49258") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Suporte Técnico</option>
                <option value="MLB63965" <?php if($item['category_id'] == "MLB63965") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Vestuário</option>
                <option value="MLB9004" <?php if($item['category_id'] == "MLB9004") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Veículos e Transportes</option>
                <option value="MLB1229" <?php if($item['category_id'] == "MLB1229") echo "selected" ?> >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Viagens e Turismo</option>
      </select>

      </p>
